# Generated by Django 3.2 on 2021-04-23 12:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translation',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
