# Generated by Django 3.2 on 2021-04-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_word_translation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='base_word',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='translation',
            new_name='translated_word',
        ),
        migrations.RemoveField(
            model_name='word',
            name='language',
        ),
        migrations.AddField(
            model_name='word',
            name='base_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base_language', to='api.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='foreign_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_language', to='api.language'),
            preserve_default=False,
        ),
    ]
